version: '3'
services:
  node_app:
    container_name: node_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=$NODE_ENV
      - APP_MONGO_USER=$APP_MONGO_USER
      - APP_MONGO_PASS=$APP_MONGO_PASS
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - WAIT_HOSTS=mongodb:27017
    ports: 
      - '3000:3000'
    links: 
      - mongodb
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js       
       
  mongodb:
    container_name: mongodb
    image: mongo
    ports: 
      - '27017:27017'
    volumes:
      - 'dbdata:/data/db'
      - "./bash/:/docker-entrypoint-initdb.d/"
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - APP_MONGO_USER=$APP_MONGO_USER
      - APP_MONGO_PASS=$APP_MONGO_PASS
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  dbdata: 
  node_modules:         