version: '3'
services:
  node_app:
    container_name: node_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - VIRTUAL_HOST=test.tinyreviews.info
      - NODE_ENV=$NODE_ENV
      - APP_MONGO_USER=$MONGO_USERNAME
      - APP_MONGO_PASS=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - WAIT_HOSTS=mongodb:27017
    ports: 
      - '80:80'
    links: 
      - mongodb
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - server_logs:/home/node/app/logs
    networks:
      - nginx-proxy
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js       
       
  mongodb:
    container_name: mongodb
    image: mongo
    # ports: 
    #   - '27017:27017'
    volumes:
      - 'dbdata_mongo:/data/db'
      #- "./bash/:/docker-entrypoint-initdb.d/"
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      #- MONGO_USERNAME=$MONGO_USERNAME
      #- MONGO_PASSWORD=$MONGO_PASSWORD
      #- APP_MONGO_USER=$APP_MONGO_USER
      #- APP_MONGO_PASS=$APP_MONGO_PASS
      #- MONGO_HOSTNAME=mongodb
      #- MONGO_PORT=$MONGO_PORT
      #- MONGO_DB=$MONGO_DB
    networks:
      - nginx-proxy
  # webserver:
  #     image: nginx:mainline-alpine
  #     container_name: webserver
  #     restart: unless-stopped
  #     ports:
  #       - "80:80"
  #     volumes:
  #       #- web-root:/var/www/html
  #       - ./nginx-conf:/etc/nginx/conf.d
  #       #- certbot-etc:/etc/letsencrypt
  #       #- certbot-var:/var/lib/letsencrypt
  #     depends_on:
  #       - node_app
  #     networks:
  #       - app-network
  # certbot:
  #     image: certbot/certbot
  #     container_name: certbot
  #     volumes:
  #       - certbot-etc:/etc/letsencrypt
  #       - certbot-var:/var/lib/letsencrypt
  #       - web-root:/var/www/html
  #     depends_on:
  #       - webserver
  #     command: certonly --webroot --webroot-path=/var/www/html --email yeakubinfire@gmail.com --agree-tos --no-eff-email --staging -d onlinepgdexam.com  -d www.onlinepgdexam.com               
networks:
  default:
    external:
      name: nginx-proxy

volumes:
  dbdata_mongo: 
  node_modules:
  server_logs:
  # certbot-etc:
  # certbot-var:
  # web-root:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/muktaking/node_project/dockerizedExamCenter/public/
  #     o: bind         