version: '3'
services:
  node_app:
    container_name: node_app
    restart: always
    bulid: .
      # context: .
      # dockerfile: Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=$NODE_ENV
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - "WAIT_HOSTS: mongodb:27017"
    ports: 
      - '3000:3000'
    links: 
      - mongodb
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network    
       
  mongodb:
    container_name: mongodb
    image: mongo
    ports: 
      - '27017:27017'
    volumes:
      - 'dbdata:/data/db'
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    networks:
      - app-network
  networks:
    app-network:
      driver: bridge

  volumes:
    dbdata:
    node_modules:         